const LANGUAGES = [
  // Tier 1 — Full Translation (20 languages)
  { code: 'en',    name: 'English',              native: 'English',           flag: '🇬🇧', tier: 1, rtl: false },
  { code: 'zh-CN', name: 'Chinese (Simplified)', native: '中文（简体）',       flag: '🇨🇳', tier: 1, rtl: false },
  { code: 'zh-TW', name: 'Chinese (Traditional)',native: '中文（繁體）',       flag: '🇹🇼', tier: 1, rtl: false },
  { code: 'es',    name: 'Spanish',              native: 'Español',           flag: '🇪🇸', tier: 1, rtl: false },
  { code: 'hi',    name: 'Hindi',                native: 'हिन्दी',             flag: '🇮🇳', tier: 1, rtl: false },
  { code: 'ar',    name: 'Arabic',               native: 'العربية',           flag: '🇸🇦', tier: 1, rtl: true  },
  { code: 'bn',    name: 'Bengali',              native: 'বাংলা',              flag: '🇧🇩', tier: 1, rtl: false },
  { code: 'pt',    name: 'Portuguese',           native: 'Português',         flag: '🇧🇷', tier: 1, rtl: false },
  { code: 'id',    name: 'Indonesian',           native: 'Bahasa Indonesia',  flag: '🇮🇩', tier: 1, rtl: false },
  { code: 'fr',    name: 'French',               native: 'Français',          flag: '🇫🇷', tier: 1, rtl: false },
  { code: 'de',    name: 'German',               native: 'Deutsch',           flag: '🇩🇪', tier: 1, rtl: false },
  { code: 'it',    name: 'Italian',              native: 'Italiano',          flag: '🇮🇹', tier: 1, rtl: false },
  { code: 'tr',    name: 'Turkish',              native: 'Türkçe',            flag: '🇹🇷', tier: 1, rtl: false },
  { code: 'pl',    name: 'Polish',               native: 'Polski',            flag: '🇵🇱', tier: 1, rtl: false },
  { code: 'hu',    name: 'Hungarian',            native: 'Magyar',            flag: '🇭🇺', tier: 1, rtl: false },
  { code: 'vi',    name: 'Vietnamese',           native: 'Tiếng Việt',        flag: '🇻🇳', tier: 1, rtl: false },
  { code: 'th',    name: 'Thai',                 native: 'ภาษาไทย',           flag: '🇹🇭', tier: 1, rtl: false },
  { code: 'ru',    name: 'Russian',              native: 'Русский',           flag: '🇷🇺', tier: 1, rtl: false },
  { code: 'ja',    name: 'Japanese',             native: '日本語',             flag: '🇯🇵', tier: 1, rtl: false },
  { code: 'ko',    name: 'Korean',               native: '한국어',             flag: '🇰🇷', tier: 1, rtl: false },

  // Tier 2 — UI + Card Fields (40 languages)
  { code: 'tl',    name: 'Filipino',             native: 'Filipino',          flag: '🇵🇭', tier: 2, rtl: false },
  { code: 'ms',    name: 'Malay',                native: 'Bahasa Melayu',     flag: '🇲🇾', tier: 2, rtl: false },
  { code: 'nl',    name: 'Dutch',                native: 'Nederlands',        flag: '🇳🇱', tier: 2, rtl: false },
  { code: 'sv',    name: 'Swedish',              native: 'Svenska',           flag: '🇸🇪', tier: 2, rtl: false },
  { code: 'no',    name: 'Norwegian',            native: 'Norsk',             flag: '🇳🇴', tier: 2, rtl: false },
  { code: 'da',    name: 'Danish',               native: 'Dansk',             flag: '🇩🇰', tier: 2, rtl: false },
  { code: 'fi',    name: 'Finnish',              native: 'Suomi',             flag: '🇫🇮', tier: 2, rtl: false },
  { code: 'ro',    name: 'Romanian',             native: 'Română',            flag: '🇷🇴', tier: 2, rtl: false },
  { code: 'cs',    name: 'Czech',                native: 'Čeština',           flag: '🇨🇿', tier: 2, rtl: false },
  { code: 'sk',    name: 'Slovak',               native: 'Slovenčina',        flag: '🇸🇰', tier: 2, rtl: false },
  { code: 'bg',    name: 'Bulgarian',            native: 'Български',         flag: '🇧🇬', tier: 2, rtl: false },
  { code: 'uk',    name: 'Ukrainian',            native: 'Українська',        flag: '🇺🇦', tier: 2, rtl: false },
  { code: 'sr',    name: 'Serbian',              native: 'Srpski',            flag: '🇷🇸', tier: 2, rtl: false },
  { code: 'hr',    name: 'Croatian',             native: 'Hrvatski',          flag: '🇭🇷', tier: 2, rtl: false },
  { code: 'el',    name: 'Greek',                native: 'Ελληνικά',          flag: '🇬🇷', tier: 2, rtl: false },
  { code: 'he',    name: 'Hebrew',               native: 'עברית',             flag: '🇮🇱', tier: 2, rtl: true  },
  { code: 'fa',    name: 'Persian',              native: 'فارسی',             flag: '🇮🇷', tier: 2, rtl: true  },
  { code: 'mn',    name: 'Mongolian',            native: 'Монгол',            flag: '🇲🇳', tier: 2, rtl: false },
  { code: 'ne',    name: 'Nepali',               native: 'नेपाली',             flag: '🇳🇵', tier: 2, rtl: false },
  { code: 'sw',    name: 'Swahili',              native: 'Kiswahili',         flag: '🇰🇪', tier: 2, rtl: false },
  { code: 'ta',    name: 'Tamil',                native: 'தமிழ்',             flag: '🇱🇰', tier: 2, rtl: false },
  { code: 'te',    name: 'Telugu',               native: 'తెలుగు',            flag: '🇮🇳', tier: 2, rtl: false },
  { code: 'mr',    name: 'Marathi',              native: 'मराठी',              flag: '🇮🇳', tier: 2, rtl: false },
  { code: 'gu',    name: 'Gujarati',             native: 'ગુજરાતી',            flag: '🇮🇳', tier: 2, rtl: false },
  { code: 'ml',    name: 'Malayalam',            native: 'മലയാളം',            flag: '🇮🇳', tier: 2, rtl: false },
  { code: 'kn',    name: 'Kannada',              native: 'ಕನ್ನಡ',             flag: '🇮🇳', tier: 2, rtl: false },
  { code: 'pa',    name: 'Punjabi',              native: 'ਪੰਜਾਬੀ',            flag: '🇮🇳', tier: 2, rtl: false },
  { code: 'ur',    name: 'Urdu',                 native: 'اردو',              flag: '🇵🇰', tier: 2, rtl: true  },
  { code: 'si',    name: 'Sinhala',              native: 'සිංහල',             flag: '🇱🇰', tier: 2, rtl: false },
  { code: 'my',    name: 'Burmese',              native: 'မြန်မာဘာသာ',        flag: '🇲🇲', tier: 2, rtl: false },
  { code: 'km',    name: 'Khmer',                native: 'ភាសាខ្មែរ',         flag: '🇰🇭', tier: 2, rtl: false },
  { code: 'lo',    name: 'Lao',                  native: 'ພາສາລາວ',           flag: '🇱🇦', tier: 2, rtl: false },
  { code: 'ka',    name: 'Georgian',             native: 'ქართული',           flag: '🇬🇪', tier: 2, rtl: false },
  { code: 'hy',    name: 'Armenian',             native: 'Հայերեն',           flag: '🇦🇲', tier: 2, rtl: false },
  { code: 'az',    name: 'Azerbaijani',          native: 'Azərbaycan',        flag: '🇦🇿', tier: 2, rtl: false },
  { code: 'kk',    name: 'Kazakh',               native: 'Қазақша',           flag: '🇰🇿', tier: 2, rtl: false },
  { code: 'uz',    name: 'Uzbek',                native: "O'zbek",            flag: '🇺🇿', tier: 2, rtl: false },
  { code: 'am',    name: 'Amharic',              native: 'አማርኛ',              flag: '🇪🇹', tier: 2, rtl: false },
  { code: 'ha',    name: 'Hausa',                native: 'Hausa',             flag: '🇳🇬', tier: 2, rtl: false },
  { code: 'yo',    name: 'Yoruba',               native: 'Yorùbá',            flag: '🇳🇬', tier: 2, rtl: false },

  // Tier 3 — Listed with English guide fallback (95 languages)
  { code: 'ig',    name: 'Igbo',                 native: 'Igbo',              flag: '🇳🇬', tier: 3, rtl: false },
  { code: 'zu',    name: 'Zulu',                 native: 'isiZulu',           flag: '🇿🇦', tier: 3, rtl: false },
  { code: 'xh',    name: 'Xhosa',                native: 'isiXhosa',          flag: '🇿🇦', tier: 3, rtl: false },
  { code: 'af',    name: 'Afrikaans',            native: 'Afrikaans',         flag: '🇿🇦', tier: 3, rtl: false },
  { code: 'so',    name: 'Somali',               native: 'Soomaali',          flag: '🇸🇴', tier: 3, rtl: false },
  { code: 'or',    name: 'Odia',                 native: 'ଓଡ଼ିଆ',              flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'as',    name: 'Assamese',             native: 'অসমীয়া',            flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'ps',    name: 'Pashto',               native: 'پښتو',              flag: '🇦🇫', tier: 3, rtl: true  },
  { code: 'tk',    name: 'Turkmen',              native: 'Türkmen',           flag: '🇹🇲', tier: 3, rtl: false },
  { code: 'ky',    name: 'Kyrgyz',               native: 'Кыргызча',          flag: '🇰🇬', tier: 3, rtl: false },
  { code: 'tg',    name: 'Tajik',                native: 'Тоҷикӣ',            flag: '🇹🇯', tier: 3, rtl: false },
  { code: 'be',    name: 'Belarusian',           native: 'Беларуская',        flag: '🇧🇾', tier: 3, rtl: false },
  { code: 'sl',    name: 'Slovenian',            native: 'Slovenščina',       flag: '🇸🇮', tier: 3, rtl: false },
  { code: 'bs',    name: 'Bosnian',              native: 'Bosanski',          flag: '🇧🇦', tier: 3, rtl: false },
  { code: 'sq',    name: 'Albanian',             native: 'Shqip',             flag: '🇦🇱', tier: 3, rtl: false },
  { code: 'mk',    name: 'Macedonian',           native: 'Македонски',        flag: '🇲🇰', tier: 3, rtl: false },
  { code: 'et',    name: 'Estonian',             native: 'Eesti',             flag: '🇪🇪', tier: 3, rtl: false },
  { code: 'lv',    name: 'Latvian',              native: 'Latviešu',          flag: '🇱🇻', tier: 3, rtl: false },
  { code: 'lt',    name: 'Lithuanian',           native: 'Lietuvių',          flag: '🇱🇹', tier: 3, rtl: false },
  { code: 'mt',    name: 'Maltese',              native: 'Malti',             flag: '🇲🇹', tier: 3, rtl: false },
  { code: 'is',    name: 'Icelandic',            native: 'Íslenska',          flag: '🇮🇸', tier: 3, rtl: false },
  { code: 'lb',    name: 'Luxembourgish',        native: 'Lëtzebuergesch',    flag: '🇱🇺', tier: 3, rtl: false },
  { code: 'ca',    name: 'Catalan',              native: 'Català',            flag: '🇪🇸', tier: 3, rtl: false },
  { code: 'gl',    name: 'Galician',             native: 'Galego',            flag: '🇪🇸', tier: 3, rtl: false },
  { code: 'eu',    name: 'Basque',               native: 'Euskara',           flag: '🇪🇸', tier: 3, rtl: false },
  { code: 'cy',    name: 'Welsh',                native: 'Cymraeg',           flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', tier: 3, rtl: false },
  { code: 'ga',    name: 'Irish',                native: 'Gaeilge',           flag: '🇮🇪', tier: 3, rtl: false },
  { code: 'fo',    name: 'Faroese',              native: 'Føroyskt',          flag: '🇫🇴', tier: 3, rtl: false },
  { code: 'ku',    name: 'Kurdish',              native: 'Kurdî',             flag: '🏴', tier: 3, rtl: false },
  { code: 'rw',    name: 'Kinyarwanda',          native: 'Kinyarwanda',       flag: '🇷🇼', tier: 3, rtl: false },
  { code: 'lg',    name: 'Luganda',              native: 'Luganda',           flag: '🇺🇬', tier: 3, rtl: false },
  { code: 'ln',    name: 'Lingala',              native: 'Lingála',           flag: '🇨🇩', tier: 3, rtl: false },
  { code: 'mg',    name: 'Malagasy',             native: 'Malagasy',          flag: '🇲🇬', tier: 3, rtl: false },
  { code: 'wo',    name: 'Wolof',                native: 'Wolof',             flag: '🇸🇳', tier: 3, rtl: false },
  { code: 'ff',    name: 'Fula',                 native: 'Fulfulde',          flag: '🌍', tier: 3, rtl: false },
  { code: 'sn',    name: 'Shona',                native: 'chiShona',          flag: '🇿🇼', tier: 3, rtl: false },
  { code: 'ny',    name: 'Chichewa',             native: 'Chichewa',          flag: '🇲🇼', tier: 3, rtl: false },
  { code: 'st',    name: 'Sesotho',              native: 'Sesotho',           flag: '🇱🇸', tier: 3, rtl: false },
  { code: 'tn',    name: 'Tswana',               native: 'Setswana',          flag: '🇧🇼', tier: 3, rtl: false },
  { code: 'om',    name: 'Oromo',                native: 'Afaan Oromoo',      flag: '🇪🇹', tier: 3, rtl: false },
  { code: 'ti',    name: 'Tigrinya',             native: 'ትግርኛ',              flag: '🇪🇷', tier: 3, rtl: false },
  { code: 'ht',    name: 'Haitian Creole',       native: 'Kreyòl ayisyen',    flag: '🇭🇹', tier: 3, rtl: false },
  { code: 'qu',    name: 'Quechua',              native: 'Quechua',           flag: '🇵🇪', tier: 3, rtl: false },
  { code: 'gn',    name: 'Guaraní',              native: "Avañe'ẽ",           flag: '🇵🇾', tier: 3, rtl: false },
  { code: 'ay',    name: 'Aymara',               native: 'Aymara',            flag: '🇧🇴', tier: 3, rtl: false },
  { code: 'jv',    name: 'Javanese',             native: 'Basa Jawa',         flag: '🇮🇩', tier: 3, rtl: false },
  { code: 'su',    name: 'Sundanese',            native: 'Basa Sunda',        flag: '🇮🇩', tier: 3, rtl: false },
  { code: 'ceb',   name: 'Cebuano',              native: 'Sinugbuanon',       flag: '🇵🇭', tier: 3, rtl: false },
  { code: 'ilo',   name: 'Ilocano',              native: 'Ilokano',           flag: '🇵🇭', tier: 3, rtl: false },
  { code: 'mi',    name: 'Māori',                native: 'Te Reo Māori',      flag: '🇳🇿', tier: 3, rtl: false },
  { code: 'sm',    name: 'Samoan',               native: 'Gagana Samoa',      flag: '🇼🇸', tier: 3, rtl: false },
  { code: 'to',    name: 'Tongan',               native: 'lea faka-Tonga',    flag: '🇹🇴', tier: 3, rtl: false },
  { code: 'fj',    name: 'Fijian',               native: 'Vosa Vakaviti',     flag: '🇫🇯', tier: 3, rtl: false },
  { code: 'tet',   name: 'Tetum',                native: 'Tetun',             flag: '🇹🇱', tier: 3, rtl: false },
  { code: 'tpi',   name: 'Tok Pisin',            native: 'Tok Pisin',         flag: '🇵🇬', tier: 3, rtl: false },
  { code: 'bi',    name: 'Bislama',              native: 'Bislama',           flag: '🇻🇺', tier: 3, rtl: false },
  { code: 'bo',    name: 'Tibetan',              native: 'བོད་སྐད་',           flag: '🏔️', tier: 3, rtl: false },
  { code: 'ug',    name: 'Uyghur',               native: 'ئۇيغۇرچە',          flag: '🏴', tier: 3, rtl: true  },
  { code: 'dz',    name: 'Dzongkha',             native: 'རྫོང་ཁ',             flag: '🇧🇹', tier: 3, rtl: false },
  { code: 'sd',    name: 'Sindhi',               native: 'سنڌي',              flag: '🇵🇰', tier: 3, rtl: true  },
  { code: 'sa',    name: 'Sanskrit',             native: 'संस्कृत',             flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'mai',   name: 'Maithili',             native: 'मैथिली',              flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'kok',   name: 'Konkani',              native: 'कोंकणी',              flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'mni',   name: 'Manipuri',             native: 'মণিপুরী',             flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'sat',   name: 'Santali',              native: 'ᱥᱟᱱᱛᱟᱲᱤ',           flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'doi',   name: 'Dogri',                native: 'डोगरी',               flag: '🇮🇳', tier: 3, rtl: false },
  { code: 'zh-HK', name: 'Cantonese',            native: '粵語',               flag: '🇭🇰', tier: 3, rtl: false },
  { code: 'cnr',   name: 'Montenegrin',          native: 'Crnogorski',        flag: '🇲🇪', tier: 3, rtl: false },
  { code: 'oc',    name: 'Occitan',              native: 'Occitan',           flag: '🇫🇷', tier: 3, rtl: false },
  { code: 'br',    name: 'Breton',               native: 'Brezhoneg',         flag: '🇫🇷', tier: 3, rtl: false },
  { code: 'sc',    name: 'Sardinian',            native: 'Sardu',             flag: '🇮🇹', tier: 3, rtl: false },
  { code: 'fy',    name: 'Frisian',              native: 'Frysk',             flag: '🇳🇱', tier: 3, rtl: false },
  { code: 'gd',    name: 'Scottish Gaelic',      native: 'Gàidhlig',          flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', tier: 3, rtl: false },
  { code: 'rm',    name: 'Romansh',              native: 'Rumantsch',         flag: '🇨🇭', tier: 3, rtl: false },
  { code: 'kw',    name: 'Cornish',              native: 'Kernewek',          flag: '🏴', tier: 3, rtl: false },
  { code: 'fur',   name: 'Friulian',             native: 'Furlan',            flag: '🇮🇹', tier: 3, rtl: false },
  { code: 'lij',   name: 'Ligurian',             native: 'Ligure',            flag: '🇮🇹', tier: 3, rtl: false },
  { code: 'vec',   name: 'Venetian',             native: 'Vèneto',            flag: '🇮🇹', tier: 3, rtl: false },
  { code: 'nap',   name: 'Neapolitan',           native: 'Napulitano',        flag: '🇮🇹', tier: 3, rtl: false },
  { code: 'bar',   name: 'Bavarian',             native: 'Boarisch',          flag: '🇩🇪', tier: 3, rtl: false },
  { code: 'pms',   name: 'Piedmontese',          native: 'Piemontèis',        flag: '🇮🇹', tier: 3, rtl: false },
  { code: 'ber',   name: 'Tamazight',            native: 'ⵜⴰⵎⴰⵣⵉⵖⵜ',         flag: '🇲🇦', tier: 3, rtl: false },
  { code: 'kab',   name: 'Kabyle',               native: 'Taqbaylit',         flag: '🇩🇿', tier: 3, rtl: false },
  { code: 'war',   name: 'Waray',                native: 'Winaray',           flag: '🇵🇭', tier: 3, rtl: false },
  { code: 'pam',   name: 'Kapampangan',          native: 'Kapampangan',       flag: '🇵🇭', tier: 3, rtl: false },
  { code: 'bcl',   name: 'Bikol',                native: 'Bikol',             flag: '🇵🇭', tier: 3, rtl: false },
  { code: 'iba',   name: 'Iban',                 native: 'Iban',              flag: '🇲🇾', tier: 3, rtl: false },
  { code: 'bug',   name: 'Buginese',             native: 'Basa Ugi',          flag: '🇮🇩', tier: 3, rtl: false },
  { code: 'ach',   name: 'Acholi',               native: 'Lwo',               flag: '🇺🇬', tier: 3, rtl: false },
  { code: 'luo',   name: 'Luo',                  native: 'Dholuo',            flag: '🇰🇪', tier: 3, rtl: false },
  { code: 'din',   name: 'Dinka',                native: 'Thuɔŋjäŋ',          flag: '🇸🇸', tier: 3, rtl: false },
  { code: 'haw',   name: 'Hawaiian',             native: 'ʻŌlelo Hawaiʻi',   flag: '🌺', tier: 3, rtl: false },
  { code: 'rap',   name: 'Rapa Nui',             native: 'Rapa Nui',          flag: '🗿', tier: 3, rtl: false },
  { code: 'gsw',   name: 'Alsatian',             native: 'Elsässisch',        flag: '🇫🇷', tier: 3, rtl: false },
  { code: 'ms-BN', name: 'Malay (Brunei)',        native: 'Bahasa Melayu (BN)',flag: '🇧🇳', tier: 3, rtl: false },
];
